name: CloudLab Runner

on:
  workflow_dispatch:

jobs:
  cloudlab:

    runs-on: ubuntu-latest

    steps:

    - name: Update
      run: sudo apt update

    - name: Install SSH
      run: |
        sudo apt install -y openssh-server curl

    - name: Create User
      run: |
        sudo useradd -m deva || true
        echo "deva:rise" | sudo chpasswd
        sudo usermod -aG sudo deva

    - name: Configure SSH
      run: |

        sudo mkdir -p /var/run/sshd

        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config

        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config

        sudo /usr/sbin/sshd

        sudo ss -tlnp

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Connect Tailscale
      run: |
        sudo tailscale up \
        --authkey=${{ secrets.TSKEY_AUTH }}

    - name: Show Info
      run: |

        echo "Tailscale IP:"
        tailscale ip

        echo "SSH Ports:"
        sudo ss -tlnp

    - name: Keep Alive
      run: sleep 21600
